package org.usfirst.frc.team486.filter;

import org.opencv.core.*;
import org.opencv.imgproc.*;

/**
* GreenFilter class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/

	//----------------------------------------------------------
	// OLD HSV THRESHOLDING VALUES
	// ----------------------------------------------------------
	// Scalar lower_hsv = new Scalar(50,20,240);
	// Scalar upper_hsv = new Scalar(90,255,255);
	
	public class Green {
	
	// ----------------------------------------------------------
	// HSV THRESHOLDING VALUES
	// ----------------------------------------------------------
	Scalar lower_hsv = new Scalar(80,25,229);
	Scalar upper_hsv = new Scalar(140,237,255);
	//opencv uses ranges (H: 0-180, S: 0-255, V:0-255)
	// ----------------------------------------------------------
	 
	 
	// ----------------------------------------------------------
	// FILTERING METHOD (applying HSV thresholding values)
	// ----------------------------------------------------------
	public void filter_hsv(Mat hsv, Mat destination){
		Core.inRange(hsv, this.lower_hsv, this.upper_hsv, destination);
	}
	// ----------------------------------------------------------




}

